./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1211-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1212-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1213-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1214-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1215-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1216-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1217-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1221-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1222-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1223-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1224-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1225-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1226-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1227-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1231-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1232-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1233-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1234-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1235-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1236-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1237-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1241-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1242-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1243-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1244-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1245-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1246-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1247-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1251-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1252-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1253-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1254-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1255-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1256-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1257-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1261-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1262-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1263-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1264-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1265-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1266-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1267-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1271-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1272-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1273-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1274-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1275-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1276-pc.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 2 -path 0 -pc 13 pc12/pc1277-pc.ispl
