./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 1 -tin 1 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 1 -tin 2 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 1 -tin 3 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 1 -tin 4 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 1 -tin 5 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 1 -tin 6 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 1 -tin 7 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 2 -tin 1 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 2 -tin 2 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 2 -tin 3 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 2 -tin 4 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 2 -tin 5 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 2 -tin 6 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 2 -tin 7 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 3 -tin 1 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 3 -tin 2 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 3 -tin 3 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 3 -tin 4 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 3 -tin 5 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 3 -tin 6 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 3 -tin 7 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 4 -tin 1 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 4 -tin 2 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 4 -tin 3 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 4 -tin 4 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 4 -tin 5 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 4 -tin 6 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 4 -tin 7 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 5 -tin 1 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 5 -tin 2 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 5 -tin 3 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 5 -tin 4 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 5 -tin 5 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 5 -tin 6 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 5 -tin 7 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 6 -tin 1 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 6 -tin 2 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 6 -tin 3 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 6 -tin 4 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 6 -tin 5 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 6 -tin 6 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 6 -tin 7 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 7 -tin 1 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 7 -tin 2 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 7 -tin 3 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 7 -tin 4 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 7 -tin 5 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 7 -tin 6 pc12.ispl
./Cabean-linux -steadystates -asynbn -newtarjan -newpred -control 3 -compositional 2 -sin 7 -tin 7 pc12.ispl
